#file: uldas/constants.py

VERSION = "2026.03.13"

# ── Language name → ISO 639-2 (bibliographic) ────────────────────────────
LANGUAGE_CODES: dict[str, str] = {
    "english": "eng",
    "spanish": "spa",
    "french": "fre",
    "german": "ger",
    "italian": "ita",
    "portuguese": "por",
    "russian": "rus",
    "japanese": "jpn",
    "chinese": "chi",
    "korean": "kor",
    "arabic": "ara",
    "hindi": "hin",
    "dutch": "dut",
    "swedish": "swe",
    "norwegian": "nor",
    "danish": "dan",
    "finnish": "fin",
    "polish": "pol",
    "czech": "cze",
    "hungarian": "hun",
    "greek": "gre",
    "turkish": "tur",
    "hebrew": "heb",
    "thai": "tha",
    "vietnamese": "vie",
    "ukrainian": "ukr",
    "bulgarian": "bul",
    "romanian": "rum",
    "slovak": "slo",
    "slovenian": "slv",
    "serbian": "srp",
    "croatian": "hrv",
    "bosnian": "bos",
    "albanian": "alb",
    "macedonian": "mac",
    "lithuanian": "lit",
    "latvian": "lav",
    "estonian": "est",
    "maltese": "mlt",
    "icelandic": "ice",
    "irish": "gle",
    "welsh": "wel",
    "basque": "baq",
    "catalan": "cat",
    "galician": "glg",
    "persian": "per",
    "urdu": "urd",
    "bengali": "ben",
    "gujarati": "guj",
    "punjabi": "pan",
    "tamil": "tam",
    "telugu": "tel",
    "kannada": "kan",
    "malayalam": "mal",
    "marathi": "mar",
    "nepali": "nep",
    "sinhalese": "sin",
    "burmese": "bur",
    "khmer": "khm",
    "lao": "lao",
    "tibetan": "tib",
    "mongolian": "mon",
    "kazakh": "kaz",
    "uzbek": "uzb",
    "kyrgyz": "kir",
    "tajik": "tgk",
    "turkmen": "tuk",
    "azerbaijani": "aze",
    "armenian": "arm",
    "georgian": "geo",
    "amharic": "amh",
    "swahili": "swa",
    "yoruba": "yor",
    "igbo": "ibo",
    "hausa": "hau",
    "somali": "som",
    "afrikaans": "afr",
    "zulu": "zul",
    "xhosa": "xho",
    "malay": "may",
    "indonesian": "ind",
    "tagalog": "tgl",
    "cebuano": "ceb",
    "javanese": "jav",
    "sundanese": "sun",
    "esperanto": "epo",
    "latin": "lat",
    "mandarin": "chi",
    "cantonese": "chi",
    "simplified chinese": "chi",
    "traditional chinese": "chi",
    "farsi": "per",
    "filipino": "tgl",
    "bahasa indonesia": "ind",
    "bahasa malaysia": "may",
    "no linguistic content": "zxx",
    # Native language names (for AVI IAS tags, etc.)
    "nederlands": "dut",
    "vlaams": "dut",
    "deutsch": "ger",
    "français": "fre",
    "español": "spa",
    "castellano": "spa",
    "italiano": "ita",
    "português": "por",
    "svenska": "swe",
    "norsk": "nor",
    "dansk": "dan",
    "suomi": "fin",
    "polski": "pol",
    "magyar": "hun",
    "türkçe": "tur",
    "čeština": "cze",
    "slovenčina": "slo",
    "slovenščina": "slv",
    "srpski": "srp",
    "hrvatski": "hrv",
    "bosanski": "bos",
    "shqip": "alb",
    "română": "rum",
    "български": "bul",
    "українська": "ukr",
    "русский": "rus",
    "ελληνικά": "gre",
    "עברית": "heb",
    "العربية": "ara",
    "日本語": "jpn",
    "中文": "chi",
    "한국어": "kor",
}

# ── ISO 639-2 (3-letter) → ISO 639-1 (2-letter) ─────────────────────────
ISO639_2_TO_1: dict[str, str] = {
    "ger": "de", "eng": "en", "spa": "es", "fre": "fr", "ita": "it",
    "por": "pt", "rus": "ru", "jpn": "ja", "kor": "ko", "chi": "zh",
    "ara": "ar", "hin": "hi", "dut": "nl", "swe": "sv", "nor": "no",
    "dan": "da", "fin": "fi", "pol": "pl", "cze": "cs", "hun": "hu",
    "gre": "el", "tur": "tr", "heb": "he", "tha": "th", "vie": "vi",
    "ukr": "uk", "bul": "bg", "rum": "ro", "slo": "sk", "slv": "sl",
    "srp": "sr", "hrv": "hr", "bos": "bs", "alb": "sq", "mac": "mk",
    "lit": "lt", "lav": "lv", "est": "et", "mlt": "mt", "ice": "is",
    "gle": "ga", "wel": "cy", "baq": "eu", "cat": "ca", "glg": "gl",
    "per": "fa", "urd": "ur", "ben": "bn", "guj": "gu", "pan": "pa",
    "tam": "ta", "tel": "te", "kan": "kn", "mal": "ml", "mar": "mr",
    "nep": "ne", "sin": "si", "bur": "my", "khm": "km", "lao": "lo",
    "tib": "bo", "mon": "mn", "kaz": "kk", "uzb": "uz", "kir": "ky",
    "tgk": "tg", "tuk": "tk", "aze": "az", "arm": "hy", "geo": "ka",
    "amh": "am", "swa": "sw", "yor": "yo", "ibo": "ig", "hau": "ha",
    "som": "so", "afr": "af", "zul": "zu", "xho": "xh", "may": "ms",
    "ind": "id", "tgl": "tl", "jav": "jv", "sun": "su", "epo": "eo",
    "lat": "la",
}

# Alternative 3-letter codes (ISO 639-2/T vs 639-2/B)
ISO639_ALTERNATIVE_CODES: dict[str, str] = {
    "deu": "de", "fra": "fr", "nld": "nl", "ces": "cs",
    "slk": "sk", "ron": "ro",
}

# ── ISO 639-1 → ISO 639-2 (reverse) ─────────────────────────────────────
ISO639_1_TO_2: dict[str, str] = {v: k for k, v in ISO639_2_TO_1.items()}

# ── Human-readable language names ────────────────────────────────────────
LANGUAGE_NAMES: dict[str, str] = {
    "eng": "English", "spa": "Spanish", "fre": "French", "ger": "German",
    "ita": "Italian", "por": "Portuguese", "rus": "Russian", "jpn": "Japanese",
    "chi": "Chinese", "kor": "Korean", "ara": "Arabic", "hin": "Hindi",
    "dut": "Dutch", "swe": "Swedish", "nor": "Norwegian", "dan": "Danish",
    "fin": "Finnish", "pol": "Polish", "cze": "Czech", "hun": "Hungarian",
    "gre": "Greek", "tur": "Turkish", "heb": "Hebrew", "tha": "Thai",
    "vie": "Vietnamese", "ukr": "Ukrainian", "bul": "Bulgarian",
    "rum": "Romanian", "slo": "Slovak", "slv": "Slovenian", "srp": "Serbian",
    "hrv": "Croatian", "bos": "Bosnian", "zxx": "No Linguistic Content",
    "alb": "Albanian", "mac": "Macedonian", "lit": "Lithuanian", "lav": "Latvian",
    "est": "Estonian", "mlt": "Maltese", "ice": "Icelandic", "gle": "Irish",
    "wel": "Welsh", "baq": "Basque", "cat": "Catalan", "glg": "Galician",
    "per": "Persian", "urd": "Urdu", "ben": "Bengali", "guj": "Gujarati",
    "pan": "Punjabi", "tam": "Tamil", "tel": "Telugu", "kan": "Kannada",
    "mal": "Malayalam", "mar": "Marathi", "nep": "Nepali", "sin": "Sinhalese",
    "bur": "Burmese", "khm": "Khmer", "lao": "Lao", "tib": "Tibetan",
    "mon": "Mongolian", "kaz": "Kazakh", "uzb": "Uzbek", "kir": "Kyrgyz",
    "tgk": "Tajik", "tuk": "Turkmen", "aze": "Azerbaijani", "arm": "Armenian",
    "geo": "Georgian", "amh": "Amharic", "swa": "Swahili", "yor": "Yoruba",
    "ibo": "Igbo", "hau": "Hausa", "som": "Somali", "afr": "Afrikaans",
    "zul": "Zulu", "xho": "Xhosa", "may": "Malay", "ind": "Indonesian",
    "tgl": "Tagalog", "jav": "Javanese", "sun": "Sundanese", "epo": "Esperanto",
    "lat": "Latin",
}

# ── Video file extensions ────────────────────────────────────────────────
VIDEO_EXTENSIONS: set[str] = {
    ".mp4", ".avi", ".mov", ".wmv", ".flv", ".webm",
    ".m4v", ".m2ts", ".mts", ".ts", ".vob",
}

# ── External subtitle file extensions ────────────────────────────────────
EXTERNAL_SUBTITLE_EXTENSIONS: set[str] = {
    ".srt", ".ass", ".ssa", ".sub", ".vtt", ".idx",
}